// lucide-react 아이콘 이름 → 컴포넌트 조회를 이 파일 한 곳으로 모은다. icon:string prop 을
// 쓰는 컴포넌트(IconBadge·Button·TextField 등)가 이 레지스트리를 통해서만 아이콘을 얻는다 —
// 여기 말고 다른 파일에서 `import { X } from "lucide-react"` 로 개별 아이콘을 부르지 않는다.
// 목록은 .curvez/design/preemie-calc/index.md `## 아이콘 목록`(32개)과 정확히 같다.
import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  Baby,
  Banknote,
  CalendarClock,
  CalendarDays,
  Check,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleCheckBig,
  CircleDashed,
  CircleDot,
  CircleHelp,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Copy,
  CopyCheck,
  Hourglass,
  Info,
  Milk,
  Minus,
  MoreVertical,
  Pencil,
  Ruler,
  Share2,
  Sparkles,
  Stethoscope,
  Syringe,
  Target,
  Trash2,
  UserRound,
  UserRoundPlus,
  Utensils,
  Weight,
  type LucideIcon,
} from "lucide-react";

export const ICONS = {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  Baby,
  Banknote,
  CalendarClock,
  CalendarDays,
  Check,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleCheckBig,
  CircleDashed,
  CircleDot,
  CircleHelp,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Copy,
  CopyCheck,
  Hourglass,
  Info,
  Milk,
  Minus,
  MoreVertical,
  Pencil,
  Ruler,
  Share2,
  Sparkles,
  Stethoscope,
  Syringe,
  Target,
  Trash2,
  UserRound,
  UserRoundPlus,
  Utensils,
  Weight,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
