/**
 * `cases/fsd-to-ddd` 의 의존성 역전 다이어그램.
 *
 * **`.svg` 파일을 `<img>` 로 부르지 않고 컴포넌트로 둔다.** 이 그림은 색을 클래스로만
 * 지정하는데(`c-frontend`·`a-dashed`·`t-primary` …), `<img>` 로 불러온 SVG 는 독립 문서라
 * 페이지의 CSS 를 못 받는다. 그래서 `public/blog/fsd-to-ddd-diagram.svg` 는 스타일 없이
 * 렌더돼 깨진 이미지로 보였다 — `naturalWidth` 가 0 이었다.
 *
 * 인라인으로 두면 `app/globals.css` 의 `.archify-diagram` 규칙을 받는다. 그 규칙은 사이트
 * 토큰을 쓰므로 라이트·다크가 같이 따라온다. 원본 archify 스타일은 자기 팔레트 변수를
 * 참조했는데, 그 색을 그대로 들여오면 중립으로 내린 사이트 배경 위에서 혼자 떠오른다.
 *
 * 범례와 인터랙션 속성(`tabindex`·`role="button"`)은 뺐다. 노드를 색으로 가르지 않으니
 * 범례에 읽을 것이 없고, 정적인 그림에 초점이 들어가면 아무 데도 못 가는 자리가 된다.
 */
export function FsdToDddDiagram() {
  return (
    <figure
      role="img"
      aria-label="Presentation 이 Application 을 호출하고 Application 은 Domain 의 SpotRepository 인터페이스만 안다. TourApiSpotRepository 와 MockSpotRepository 두 Infrastructure 구현이 아래에서 위로 Domain 을 향해 점선 화살표로 이어진다."
    >
      <svg
        className="diagram"
        style={{ width: "100%", height: "auto", display: "block" }}
        viewBox="0 0 1120 620"
        role="img"
        lang="en"
        aria-labelledby="archify-diagram-title archify-diagram-description"
        data-preset="classic"
        data-quality-profile="showcase"
      >
        <title id="archify-diagram-title">
          인터페이스를 도메인에 두면 화살표가 뒤집힌다
        </title>
        <desc id="archify-diagram-description">
          An architecture diagram generated by Archify.
        </desc>
        <defs>
          <marker
            id="arrowhead"
            markerWidth="10"
            markerHeight="7"
            refX="9"
            refY="3.5"
            orient="auto"
          >
            <polygon points="0 0, 10 3.5, 0 7" className="m-default" />
          </marker>
          <marker
            id="arrowhead-emphasis"
            markerWidth="10"
            markerHeight="7"
            refX="9"
            refY="3.5"
            orient="auto"
          >
            <polygon points="0 0, 10 3.5, 0 7" className="m-emphasis" />
          </marker>
          <marker
            id="arrowhead-security"
            markerWidth="10"
            markerHeight="7"
            refX="9"
            refY="3.5"
            orient="auto"
          >
            <polygon points="0 0, 10 3.5, 0 7" className="m-security" />
          </marker>
          <marker
            id="arrowhead-dashed"
            markerWidth="10"
            markerHeight="7"
            refX="9"
            refY="3.5"
            orient="auto"
          >
            <polygon points="0 0, 10 3.5, 0 7" className="m-dashed" />
          </marker>
          <pattern id="grid" patternUnits="userSpaceOnUse">
            <path d="M 40 0 L 0 0 0 40" className="c-grid" strokeWidth="0.5" />
          </pattern>
        </defs>
        <rect width="100%" height="100%" fill="url(#grid)" />
        <path
          data-edge-from="presentation"
          data-edge-to="application"
          data-edge-label="호출"
          data-edge-key="0"
          data-edge-id="pres-to-app"
          data-composition-points="250,158;330,158"
          d="M 250 158 L 330 158"
          className="a-emphasis"
          strokeWidth="1.8"
          markerEnd="url(#arrowhead-emphasis)"
        />
        <path
          data-edge-from="application"
          data-edge-to="domain"
          data-edge-label="인터페이스만 안다"
          data-edge-key="1"
          data-edge-id="app-to-domain"
          data-composition-points="510,158;640,158"
          d="M 510 158 L 640 158"
          className="a-emphasis"
          strokeWidth="1.8"
          markerEnd="url(#arrowhead-emphasis)"
        />
        <path
          data-edge-from="tourapi"
          data-edge-to="domain"
          data-edge-label="구현"
          data-edge-key="2"
          data-edge-id="tourapi-to-domain"
          data-composition-points="610,420;610,308;743,308;743,196"
          d="M 610 420 L 610 316 Q 610 308 618 308 L 735 308 Q 743 308 743 300 L 743 196"
          className="a-dashed"
          strokeWidth="1.5"
          markerEnd="url(#arrowhead-dashed)"
        />
        <path
          data-edge-from="mock"
          data-edge-to="domain"
          data-edge-label="구현"
          data-edge-key="3"
          data-edge-id="mock-to-domain"
          data-composition-points="910,420;910,308;757,308;757,196"
          d="M 910 420 L 910 316 Q 910 308 902 308 L 765 308 Q 757 308 757 300 L 757 196"
          className="a-dashed"
          strokeWidth="1.5"
          markerEnd="url(#arrowhead-dashed)"
        />
        <g
          id="node-presentation"
          data-node-id="presentation"
          data-node-label="Presentation"
          aria-label="Focus Presentation, 화면 · 컴포넌트, Architecture component"
          data-node-kind="frontend"
          data-node-sublabel="화면 · 컴포넌트"
          data-node-context="Architecture component"
        >
          <title>Presentation · 화면 · 컴포넌트 · Architecture component</title>
          <rect
            x="70"
            y="120"
            width="180"
            height="76"
            rx="6"
            className="c-mask"
          />
          <rect
            x="70"
            y="120"
            width="180"
            height="76"
            rx="6"
            className="c-frontend"
            strokeWidth="1.5"
          />
          <g
            aria-hidden="true"
            data-semantic-sigil="frontend"
            className="semantic-sigil s-frontend"
            transform="translate(76 126) scale(0.6875)"
          >
            <rect x="2" y="3" width="12" height="10" rx="2" />
            <path d="M2 6.5h12" />
            <circle cx="4.1" cy="4.8" r=".7" className="sigil-fill" />
            <circle cx="6.3" cy="4.8" r=".7" className="sigil-fill" />
          </g>
          <text
            data-node-label=""
            data-detail-anchor=""
            x="160"
            y="156"
            className="t-primary"
            fontSize="11"
            fontWeight="600"
            textAnchor="middle"
          >
            Presentation
          </text>
          <text
            data-detail="context"
            x="160"
            y="172"
            className="t-muted"
            fontSize="9"
            textAnchor="middle"
          >
            화면 · 컴포넌트
          </text>
        </g>
        <g
          id="node-application"
          data-node-id="application"
          data-node-label="Application"
          aria-label="Focus Application, 유스케이스, Architecture component"
          data-node-kind="backend"
          data-node-sublabel="유스케이스"
          data-node-context="Architecture component"
        >
          <title>Application · 유스케이스 · Architecture component</title>
          <rect
            x="330"
            y="120"
            width="180"
            height="76"
            rx="6"
            className="c-mask"
          />
          <rect
            x="330"
            y="120"
            width="180"
            height="76"
            rx="6"
            className="c-backend"
            strokeWidth="1.5"
          />
          <g
            aria-hidden="true"
            data-semantic-sigil="backend"
            className="semantic-sigil s-backend"
            transform="translate(336 126) scale(0.6875)"
          >
            <path d="M6 3 3 8l3 5M10 3l3 5-3 5" />
          </g>
          <text
            data-node-label=""
            data-detail-anchor=""
            x="420"
            y="156"
            className="t-primary"
            fontSize="11"
            fontWeight="600"
            textAnchor="middle"
          >
            Application
          </text>
          <text
            data-detail="context"
            x="420"
            y="172"
            className="t-muted"
            fontSize="9"
            textAnchor="middle"
          >
            유스케이스
          </text>
        </g>
        <g
          id="node-domain"
          data-node-id="domain"
          data-node-label="Domain"
          aria-label="Focus Domain, SpotRepository 인터페이스, Architecture component"
          data-node-kind="external"
          data-node-sublabel="SpotRepository 인터페이스"
          data-node-context="Architecture component"
        >
          <title>
            Domain · SpotRepository 인터페이스 · Architecture component
          </title>
          <rect
            x="640"
            y="120"
            width="220"
            height="76"
            rx="6"
            className="c-mask"
          />
          <rect
            x="640"
            y="120"
            width="220"
            height="76"
            rx="6"
            className="c-external"
            strokeWidth="1.5"
          />
          <g
            aria-hidden="true"
            data-semantic-sigil="external"
            className="semantic-sigil s-external"
            transform="translate(646 126) scale(0.6875)"
          >
            <rect x="2.5" y="5" width="8.5" height="8" rx="1.5" />
            <path d="M8 2.5h5.5V8M13.5 2.5 7.5 8.5" />
          </g>
          <text
            data-node-label=""
            data-detail-anchor=""
            x="750"
            y="156"
            className="t-primary"
            fontSize="11"
            fontWeight="600"
            textAnchor="middle"
          >
            Domain
          </text>
          <text
            data-detail="context"
            x="750"
            y="172"
            className="t-muted"
            fontSize="9"
            textAnchor="middle"
          >
            SpotRepository 인터페이스
          </text>
        </g>
        <g
          id="node-tourapi"
          data-node-id="tourapi"
          data-node-label="TourApiSpotRepository"
          aria-label="Focus TourApiSpotRepository, Infrastructure · 실제 API, Architecture component"
          data-node-kind="cloud"
          data-node-sublabel="Infrastructure · 실제 API"
          data-node-context="Architecture component"
        >
          <title>
            TourApiSpotRepository · Infrastructure · 실제 API · Architecture
            component
          </title>
          <rect
            x="500"
            y="420"
            width="220"
            height="76"
            rx="6"
            className="c-mask"
          />
          <rect
            x="500"
            y="420"
            width="220"
            height="76"
            rx="6"
            className="c-cloud"
            strokeWidth="1.5"
          />
          <g
            aria-hidden="true"
            data-semantic-sigil="cloud"
            className="semantic-sigil s-cloud"
            transform="translate(506 426) scale(0.6875)"
          >
            <path d="M4.3 12.5h7.3a2.4 2.4 0 0 0 .2-4.8 4 4 0 0 0-7.5-1.3A3.1 3.1 0 0 0 4.3 12.5Z" />
          </g>
          <text
            data-node-label=""
            data-detail-anchor=""
            x="610"
            y="456"
            className="t-primary"
            fontSize="11"
            fontWeight="600"
            textAnchor="middle"
          >
            TourApiSpotRepository
          </text>
          <text
            data-detail="context"
            x="610"
            y="472"
            className="t-muted"
            fontSize="9"
            textAnchor="middle"
          >
            Infrastructure · 실제 API
          </text>
        </g>
        <g
          id="node-mock"
          data-node-id="mock"
          data-node-label="MockSpotRepository"
          aria-label="Focus MockSpotRepository, Infrastructure · 테스트용, Architecture component"
          data-node-kind="database"
          data-node-sublabel="Infrastructure · 테스트용"
          data-node-context="Architecture component"
        >
          <title>
            MockSpotRepository · Infrastructure · 테스트용 · Architecture
            component
          </title>
          <rect
            x="800"
            y="420"
            width="220"
            height="76"
            rx="6"
            className="c-mask"
          />
          <rect
            x="800"
            y="420"
            width="220"
            height="76"
            rx="6"
            className="c-database"
            strokeWidth="1.5"
          />
          <g
            aria-hidden="true"
            data-semantic-sigil="database"
            className="semantic-sigil s-database"
            transform="translate(806 426) scale(0.6875)"
          >
            <ellipse cx="8" cy="4" rx="5" ry="2" />
            <path d="M3 4v8c0 1.1 2.2 2 5 2s5-.9 5-2V4M3 8c0 1.1 2.2 2 5 2s5-.9 5-2" />
          </g>
          <text
            data-node-label=""
            data-detail-anchor=""
            x="910"
            y="456"
            className="t-primary"
            fontSize="11"
            fontWeight="600"
            textAnchor="middle"
          >
            MockSpotRepository
          </text>
          <text
            data-detail="context"
            x="910"
            y="472"
            className="t-muted"
            fontSize="9"
            textAnchor="middle"
          >
            Infrastructure · 테스트용
          </text>
        </g>
        <g
          data-detail="context"
          data-edge-from="presentation"
          data-edge-to="application"
          data-edge-label="호출"
          data-edge-key="0"
          data-edge-id="pres-to-app"
        >
          <rect
            x="275"
            y="138"
            width="30"
            height="14"
            rx="3"
            className="c-mask"
          />
          <text
            x="290"
            y="148"
            className="t-backend"
            fontSize="8"
            textAnchor="middle"
          >
            호출
          </text>
        </g>
        <g
          data-detail="context"
          data-edge-from="application"
          data-edge-to="domain"
          data-edge-label="인터페이스만 안다"
          data-edge-key="1"
          data-edge-id="app-to-domain"
        >
          <rect
            x="529.2"
            y="138"
            width="91.6"
            height="14"
            rx="3"
            className="c-mask"
          />
          <text
            x="575"
            y="148"
            className="t-backend"
            fontSize="8"
            textAnchor="middle"
          >
            인터페이스만 안다
          </text>
        </g>
        <g
          data-detail="context"
          data-edge-from="tourapi"
          data-edge-to="domain"
          data-edge-label="구현"
          data-edge-key="2"
          data-edge-id="tourapi-to-domain"
        >
          <rect
            x="661.5"
            y="288"
            width="30"
            height="14"
            rx="3"
            className="c-mask"
          />
          <text
            x="676.5"
            y="298"
            className="t-messagebus"
            fontSize="8"
            textAnchor="middle"
          >
            구현
          </text>
        </g>
        <g
          data-detail="context"
          data-edge-from="mock"
          data-edge-to="domain"
          data-edge-label="구현"
          data-edge-key="3"
          data-edge-id="mock-to-domain"
        >
          <rect
            x="818.5"
            y="288"
            width="30"
            height="14"
            rx="3"
            className="c-mask"
          />
          <text
            x="833.5"
            y="298"
            className="t-messagebus"
            fontSize="8"
            textAnchor="middle"
          >
            구현
          </text>
        </g>
      </svg>
      <figcaption>
        인터페이스를 Domain 에 두면 Infrastructure 쪽 화살표가 위로 올라간다.
      </figcaption>
    </figure>
  );
}
